<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<nav class="navbar navbar-dark bg-dark fixed-top">
  <a class="navbar-brand"href="/">
    <img class="mr-1" src="icon/pepper.png">
    <span>Jalapeñcode</span>
  </a>
</nav>

  <div class="container  main-container">
    <div class="text-center">
      <h1>404</h1>
    </div>
  </div>

<?php include 'view/_footer.phtml'; ?>
</body>
</html>
