<nav id="navbar" class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
  <a class="navbar-brand font-weight-bold" href="/">
    <img class="mr-1" src="icon/pepper.png" />
    <span>Jalapeñcode</span>
  </a>
  <ul class="navbar-nav">
    <li class="nav-item"><a class="nav-link" href="about">About</a></li>
  </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav align-items-center ml-auto">
      <li class="nav-item mr-3">
        <div id="search" class="nav-link d-flex rounded bg-white align-items-center">
          <svg class="searchSVG" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
              <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
              <path d="M0 0h24v24H0z" fill="none"/>
          </svg>
          <input id="searchText" type="text" placeholder="Search">
          <svg id="searchClear" class="searchSVG pointer-hand invisible" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
              <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
              <path d="M0 0h24v24H0z" fill="none"/>
          </svg>
        </div>
      </li>
      <li class="nav-item">
        <a href="cart">
          <button id="cartButton" class="navbar-btn-dark btn btn-dark">
            <span id="cartButtonCount" class="d-none cart-count text-warning">0</span>
            <img id="cartButtonImage" src="icon/shopping_cart.png"/>
            <span id="cartButtonText" class="text-light">Cart</span>
          </button>
        </a>
      </li>
      <li class="nav-item">
        <div class="dropdown">
          <button id="accountButton" class="navbar-btn-dark btn btn-dark dropdown-toggle" data-toggle="dropdown">
            <img id="accountButtonImage" src="icon/account.png"/>
          </button>

          <?php if (isset($_SESSION['userid'])) {
            $userid = $_SESSION['userid'];
            $sql = "SELECT fname, lname FROM ACCOUNT WHERE id='{$userid}'";
            $result = $conn->query($sql);
            if (!$result) {
              echo $sql . "Query failed" . $conn->error . PHP_EOL;
            }
            $row = $result->fetch_assoc();
            $fname = $row['fname'];
            $lname = $row['lname'];
            echo
            '<div class="dropdown-menu dropdown-menu-right">
              <h6 class="px-3 pt-2">Hello, '.$fname.'</h6>
              <a class="dropdown-item" href="account">Account</a>
              <a class="dropdown-item" href="orders">Orders</a>
              <div class="dropdown-divider"></div>
              <div class="px-2 py-1">
                <button id="logoutBtn" class="btn btn-warning w-100">Sign out</button>
              </div>
            </div>';
          } else {
            echo
            '<div class="dropdown-menu dropdown-menu-right">
              <form id="login" class="px-2 py-1" action="login" method="post">
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="loginUsername" name="username" placeholder="Username" required>
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="loginPassword" name="password" placeholder="Password" required>
                  </div>
                  <div id="loginMessage" class="small"></div>
                  <button type="submit" class="btn btn-warning w-100">Sign in</button>
              </form>
              <div class="dropdown-divider"></div>
              <span class="px-2 small">New here?</span>
              <a class="small" href="/register">Register</a>
            </div>';
          }
          ?>
        </div>
      </li>
    </ul>
  </div>
</nav>
