<?php 
if (session_status() == PHP_SESSION_NONE) {
    session_start();
} 
?>
<nav id="navbar" class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
  <a class="navbar-brand font-weight-bold" href="/">
    <img class="mr-1" src="icon/pepper.png" />
    <span>Jalapeñcode</span>
  </a>
  <ul class="navbar-nav">
    <li class="nav-item"><a class="nav-link" href="about">About</a></li>
  </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav align-items-center ml-auto">
      <li class="nav-item mr-3">
        <div id="search" class="nav-link d-flex rounded bg-white align-items-center">
          <svg class="searchSVG" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
              <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
              <path d="M0 0h24v24H0z" fill="none"/>
          </svg>
          <input id="searchText" type="text" placeholder="Search" />
          <svg id="searchClear" class="searchSVG pointer-hand invisible" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
              <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
              <path d="M0 0h24v24H0z" fill="none"/>
          </svg>
            <!--<span class="input-group-btn">
              <button id="searchApplyButton" class="btn btn-warning" type="button">Go!</button>
            </span>-->
        </div>
      </li>
      <li class="nav-item">
        <a href="cart">
          <button id="cartButton" class="navbar-btn-dark btn btn-dark">
            <span id="cartButtonCount" class="d-none cart-count text-warning">0</span>
            <img id="cartButtonImage" src="icon/shopping_cart.png"/>
            <span id="cartButtonText" class="text-light">Cart</span>
          </button>
        </a>
      </li>
      <li class="nav-item">
        <?php 
        // If user is logged in, show logout button as well as link to user's account information
        if(isset($_SESSION['username']) && $_SESSION['username'] != ""){
            echo '<a href="account_setting">';
            echo '<button class="btn btn-warning mx-2">' .  $_SESSION['username'] . '</button>';
            echo '</a>';
            echo '<a href="logout">';
            echo '<button class="btn btn-warning mx-2" >Logout</button>';
            echo '</a>';
        }else{
         // User not log in
            echo '<a href="account">';
            echo '<button class="btn btn-warning">Login/Sign-up</button>';
            echo '</a>';    
        }
        ?>
            
           
           </button>
          </a>
          
        
      </li>
      



      <!--<li class="nav-item">
        <div class="dropdown">
          <button id="accountButton" class="navbar-btn-dark btn btn-dark dropdown-toggle" data-toggle="dropdown">
            <img id="accountButtonImage" src="icon/account.png"/>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a class=dropdown-item href="#">Test1</a>
            <a class=dropdown-item href="#">Test2</a>
          </div>
        </div>
      </li>-->
    </ul>
  </div>
</nav>
