<!DOCTYPE html>
<html lang="en">
<?php include '_head.phtml'; ?>
<body>
<?php include '_navbar.phtml'; ?>

  <div class="container  main-container">

    <div class="text-center mt-5">
      <h3 class="underline">Technology Profile</h3>
      <p>Jalapeñcode is built using:</p>
      <div class="mt-1">PHP</div>
      <div class="mt-1">MySQL</div>
      <div class="mt-1">Bootstrap</div>
      <div class="mt-1">jQuery</div>
    </div>

    <div class="text-center mt-5">
      <h3 class="underline">Icons</h3>
        <div class="mt-3">
          <div class="d-flex flex-row justify-content-center align-items-center">
            <div class="icon-thumbnail">
              <img src="../icon/about_fire.png"/>
            </div>
            <div class="icon-thumbnail">
              <img src="../icon/about_shopping_cart.png"/>
            </div>
            <div class="icon-thumbnail">
              <img src="../icon/about_account.png"/>
            </div>
            <div class="icon-thumbnail">
              <img src="../icon/about_search.png"/>
            </div>
          </div>
          <div>
            <span>designed by <a href="https://material.io/icons/">Google Material Icons</a></span>
          </div>
        </div>
        <div class="mt-3">
          <div class="icon-thumbnail">
            <img src="../icon/pepper.png"/>
          </div>
          <div>
            <span> designed by Freepik from <a href="http://www.flaticon.com/">Flaticon</a></span>
          </div>
        </div>
        <div>
      </div>
    </div>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include '_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
