<!DOCTYPE html>
<html lang="en">
<?php include '_head.phtml'; ?>
<body>
<?php include '_navbar.phtml'; ?>

  <div id="mainContainer" class="container">

    <div class="text-center">
      <h3>Technology Profile</h3>
      <p>Jalapeñcode is built using the following:</p>
      <div class="mt-1">PHP</div>
      <div class="mt-1">MySQL</div>
      <div class="mt-1">Bootstrap</div>
      <div class="mt-1">jQuery</div>
    </div>

    <div class="text-center mt-5">
      <h3>Icons</h3>
        <div class="mt-3">
          <div class="d-flex flex-row justify-content-center align-items-center">
            <div>
              <svg class="fire" fill="#000000" height="48" viewBox="0 0 24 24" width="48" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.5.67s.74 2.65.74 4.8c0 2.06-1.35 3.73-3.41 3.73-2.07 0-3.63-1.67-3.63-3.73l.03-.36C5.21 7.51 4 10.62 4 14c0 4.42 3.58 8 8 8s8-3.58 8-8C20 8.61 17.41 3.8 13.5.67zM11.71 19c-1.78 0-3.22-1.4-3.22-3.14 0-1.62 1.05-2.76 2.81-3.12 1.77-.36 3.6-1.21 4.62-2.58.39 1.29.59 2.65.59 4.04 0 2.65-2.15 4.8-4.8 4.8z"/>
                <path d="M0 0h24v24H0z" fill="none"/>
              </svg>
            </div>
            <div>
              <img src="../icon/shopping_cart_black.png"/>
            </div>
        </div>
          <div>
            <span>designed by <a href="https://material.io/icons/">Google Material Icons</a></span>
          </div>
        </div>
        <div class="mt-3">
          <img src="../icon/pepper.png"/>
          <div>
            <span> designed by Freepik from <a href="http://www.flaticon.com/">Flaticon</a></span>
          </div>
        </div>
        <div>
      </div>
    </div>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include '_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
