<!DOCTYPE html>
<html lang="en">
<?php include '_head.phtml'; ?>
<body>
<?php include '_navbar.phtml'; ?>

  <div id="mainContainer" class="container">

    <div class="text-center">
      <div>
        <img class="img-thumbnail" src="../icon/pepper.png">
        <span> designed by Freepik from <a href="http://www.flaticon.com/">Flaticon</a></span>
      </div>
    </div>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include '_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
