<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">
    <div class="starter-template">
      <h1></h1>
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>

    <form id="accountForm" action="/updateAccount" method="post">
      <div class='d-flex flex-column'>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First name" value='<?php echo $fname; ?>' required>
          </div>
          <div class="form-group col-md-6">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last name" value='<?php echo $lname; ?>' required>
          </div>
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="Email" value='<?php echo $email; ?>' required>
        </div>
        <div class="form-group">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" value='<?php echo $addr; ?>' required>
        </div>
        <div class="form-group">
          <label for="address2">Address 2</label>
          <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment, studio, or floor" value='<?php echo $addr2; ?>'>
        </div>
        <div class="form-group">
          <label for="city">City</label>
          <input type="text" class="form-control" id="city" name="city" placeholder="City" value='<?php echo $city; ?>' required>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="state">State</label>
            <select id="state" name="state" class="form-control" required>
              <option value="">Choose...</option>
              <option value="CA" <?php if ($state == 'CA') echo 'selected'; ?>>CA</option>
            </select>
          </div>
          <div class="form-group col-md-6">
            <label for="zip">Zip</label>
            <input type="text" pattern="[0-9]{5}" class="form-control" id="zip" name="zip" placeholder="#####" value='<?php echo $zip; ?>' required>
          </div>
        </div>
        <div class="form-row">
          <button type="submit" class="btn btn-warning">Update</button>
        </div>
      </div>
    </form>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
