<?php 
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

$sql = "SELECT * FROM account WHERE username = '{$_SESSION['username']}'";
$result = $conn->query($sql);
if(!$result){
    echo "Fail to execute: " . $sql . $conn->error . "<br />";
}else{
    $row = $result->fetch_assoc();
}
?>
<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">
    <div class="starter-template">
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>
    <h1>Update Account</h1>
    <form action="/update_account" method="post">
      <div class='d-flex'>
        <div class='flex-5'>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="firstName">First name</label>
              <input type="text" class="form-control" id="firstName" name="firstName" value="<?php echo $row['fname'];?>"/>
            </div>
            <div class="form-group col-md-6">
              <label for="lastName">Last name</label>
              <input type="lastName" class="form-control" id="lastName" name="lastName" value="<?php echo $row['lname'];?>" />
            </div>
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="<?php echo $row['email'];?>" />
          </div>
          <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address" value="<?php echo $row['addr'];?>" />
          </div>
          <div class="form-group">
            <label for="address2">Address 2</label>
            <input type="text" class="form-control" id="address2" name="address2" value="<?php echo $row['addr_2'];?>" />
          </div>
          <div class="form-group">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city" value="<?php echo $row['addr_city'];?>" />
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="state">State</label>
              <select id="state" name="state" class="form-control">
                <option value="">Choose...</option>
                <option value="CA" selected>CA</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="zip">Zip</label>
              <input type="text" pattern="[0-9]{5}" class="form-control" id="zip" name="zip" value="<?php echo $row['addr_zipcode'];?>" />
            </div>
          </div>
        </div>
        <div id="" class='rounded fit-content-height border px-2 py-3 flex-2 ml-5'>
          <button id="" type='submit' name="update_submit" class='btn btn-warning px-2 w-100' >Update</button>


        </div>
      </div>
    </form>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
