<!DOCTYPE html>
<html lang="en">
<?php include '_head.phtml'; ?>
<body>
<?php include '_navbar.phtml'; ?>

  <div class="container  main-container">
    <div class="starter-template">
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>
    <div id="cartList"></div>
  </div>

<?php include '_footer.phtml'; ?>

<?php include '_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
