<!DOCTYPE html>
<html lang="en">
<?php include '_head.phtml'; ?>
<body>
<?php include '_navbar.phtml'; ?>

  <div class="container  main-container">
    <div class="starter-template">
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>
    <div>
      <table id="cartList" class="w-100">
        <tr class="border border-secondary border-top-0 border-left-0 border-right-0">
          <th><h2>Shopping Cart</h2></th>
          <th class="text-secondary">Price</th>
          <th class="text-secondary">Quantity</th>
        </tr>
      </table>
      <div id="subtotal" class="d-none text-right mt-2">
        <span class="h4">Subtotal (<span id="cartPageCount">0</span> items):
            <span id="subtotalValue" class="text-danger">$0.00</span>
        </span>
      </div>
    </div>
  </div>

<?php include '_footer.phtml'; ?>

<?php include '_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
