<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">
    <div class="starter-template">
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>

    <form action="/submitOrder" method="post">
      <div class='d-flex'>
        <div class='flex-5'>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="firstName">First name *</label>
              <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First name" required>
            </div>
            <div class="form-group col-md-6">
              <label for="lastName">Last name *</label>
              <input type="lastName" class="form-control" id="lastName" name="lastName" placeholder="Last name" required>
            </div>
          </div>
          <div class="form-group">
            <label for="email">Email *</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
          </div>
          <div class="form-group">
            <label for="address">Address *</label>
            <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" required>
          </div>
          <div class="form-group">
            <label for="address2">Address 2</label>
            <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment, studio, or floor">
          </div>
          <div class="form-group">
            <label for="city">City *</label>
            <input type="text" class="form-control" id="city" name="city" placeholder="City" required>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="state">State *</label>
              <select id="state" name="state" class="form-control" required>
                <option value="" selected>Choose...</option>
                <option value="CA">CA</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="zip">Zip *</label>
              <input type="text" pattern="[0-9]{5}" class="form-control" id="zip" name="zip" placeholder="#####" required>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="ccNumber">Credit Card Number *</label>
              <input type="text" class="form-control" id="ccNumber" name="ccNumber" placeholder="#### #### #### ####" required>
            </div>
            <div class="form-group col-md-6">
              <label for="ccCVV">CVV *</label>
              <input type="text" class="form-control" id="ccCVV" name="ccCVV" placeholder="###" required>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="ccMonth">Exp. Month *</label>
              <select id="ccMonth" name="ccMonth" class="form-control" required>
                <option value="" selected>Choose...</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="ccYear">Exp. Year *</label>
              <input type="number" class="form-control" id="ccYear" name="ccYear" placeholder="####" min="2017" max="9999" required>
            </div>
          </div>
        </div>
        <div id="orderSummary" class='rounded fit-content-height border px-2 py-3 flex-2 ml-5'>
          <button id="orderBtn" type='submit' class='btn btn-warning px-2 w-100' <?php if ($total == 0) echo "disabled" ?>>Submit order</button>

          <div class="mt-3 d-flex flex-column justify-content-center">
            <div>
              <span class="h6">Order Summary</span>
            </div>
            <div>
              <div class="d-flex">
                <span class="mr-auto">Items: </span>
                <span id="checkOutSubtotal">$<?php echo number_format($subtotal, 2, '.', ',') ?></span>
              </div>
              <div class="d-flex">
                <span class="mr-auto">Tax &amp; Handling: </span>
                <span id="checkOutTax">$<?php echo number_format($tax, 2, '.', ',') ?></span>
              </div>
            </div>
            <div class="mt-3 pt-3 d-flex border border-left-0 border-right-0 border-bottom-0">
              <span class="text-danger h4 mr-auto">Order Total: </span>
              <span id="checkOutTotal" class="text-danger h4">$<?php echo number_format($total, 2, '.', ',') ?></span>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
