<?php 
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
?>
<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>
<!--<?php echo $_SESSION['login'] . $_SESSION['username']; ?>-->

  <div class="container main-container">
    <div class="starter-template">
      <h1>Jalapeñcode</h1>
    </div>

<?php include 'view/_filter.phtml'; ?>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>

    <div id="productGrid"></div>
  </div>

  <input id="searchString" type=hidden value=<?php echo $searchString; ?>>
<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
