<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">
    <div class="starter-template">
      <h1>Jalapeñcode</h1>
      <p class="lead">An awesome project!</p>
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>

    <div id="filter"></div>
    <div id="productGrid"></div>
  </div>

  <input id="searchString" type=hidden value=<?php echo $searchString; ?>>
<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
