<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>

    <div id="productPage" class="d-flex mt-4">
      <div>
        <img id="landingImage" src="<?php echo $item->image ?>" alt="<?php echo $item->product_name ?>">
      </div>
      <div>
        <div class="d-flex">
          <div>
            <h2><?php echo $item->product_name ?></h2>
          </div>
          <div class="ml-3 align-self-center">
            <?php for ($i=0; $i<$item->heat_id; $i++) {
              echo "<svg class='fire' height='20' viewBox='0 0 24 24' width='20' xmlns='http://www.w3.org/2000/svg'>";
              echo "<path d='M13.5.67s.74 2.65.74 4.8c0 2.06-1.35 3.73-3.41 3.73-2.07 0-3.63-1.67-3.63-3.73l.03-.36C5.21 7.51 4 10.62 4 14c0 4.42 3.58 8 8 8s8-3.58 8-8C20 8.61 17.41 3.8 13.5.67zM11.71 19c-1.78 0-3.22-1.4-3.22-3.14 0-1.62 1.05-2.76 2.81-3.12 1.77-.36 3.6-1.21 4.62-2.58.39 1.29.59 2.65.59 4.04 0 2.65-2.15 4.8-4.8 4.8z'/>";
              echo "<path d='M0 0h24v24H0z' fill='none'/>";
              echo "</svg>";
            }?>
          </div>
        </div>
        <div class="mt-1 pl-3">
          <span><?php echo $item->description ?></span>
        </div>
        <div class="mt-3 d-flex">
          <div class="mr-auto">
            <span class="text-secondary">Price: </span>
            <span class="text-danger h4">$<?php echo $item->price ?></span>
          </div>
          <div>
            <span class="text-secondary">Quantity remaining: </span>
            <span id="productQuantity" class="h5"><?php echo $item->quantity ?></span>
          </div>
        </div>
        <div class="d-flex justify-content-end">
          <button class='btn-cart-add btn btn-warning text-dark m-2' <?php if ($item->quantity <= 0) echo "disabled" ?>>Add to cart</button>
        </div>
      </div>
    </div>
  </div>

  <input type="hidden" id="id" value="<?php echo $item->id ?>">

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
