<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>

    <div id="productPage">
      <table class="table">
        <thead>
          <th>Attribute</th>
          <th>Value</th>
        </thead>
        <tbody>
          <tr>
            <td><span>Name</span></td>
            <td><span><?php echo $item->product_name ?></td>
          </tr>
          <tr>
            <td><span>Description</span></td>
            <td><span><?php echo $item->description ?></span></td>
          </tr>
          <tr>
            <td><span>Price</span></td>
            <td><span><?php echo $item->price ?></span></td>
          </tr>
          <tr>
            <td><span>Heat</span></td>
            <td><span><?php echo $item->heat_id ?></span></td>
          </tr>
          <tr>
            <td><span>Quantity</span></td>
            <td><span id="productQuantity"><?php echo $item->quantity ?></span></td>
          </tr>
          <tr>
            <td><span>Image</span></td>
            <td><img class="PG-card-image" src="<?php echo $item->image ?>"></td>
          </tr>
          <tr>
            <td><button class='btn-cart-add btn btn-warning text-dark m-2'>Add to cart</button></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
