<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">
    <div class="starter-template">
      <h1>Order processed!</h1>
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>
    <div class='loader'>Loading...</div>

    <div class="d-flex justify-content-center">
      <a class="pointer-hand" href="/">Return to main page</a>
    </div>

    <?php /*/echo $customerID . "<br/>" ?>
    <?php echo $firstName . "<br/>" ?>
    <?php echo $lastName . "<br/>" ?>
    <?php echo $address . "<br/>" ?>
    <?php echo $address2 . "<br/>" ?>
    <?php echo $city . "<br/>" ?>
    <?php echo $state . "<br/>" ?>
    <?php echo $zip . "<br/>" */?>

  </div>

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
