<!DOCTYPE html>
<html lang="en">
<?php include 'view/_head.phtml'; ?>
<body>
<?php include 'view/_navbar.phtml'; ?>

  <div class="container main-container">
    <div class="starter-template">
      <h1>Register</h1>
    </div>

    <div class="message text-center">
      <noscript>JavaScript must be enabled!</noscript>
    </div>

    <form id="registerForm" action="registerUser" method="post">
      <div class="d-flex flex-column">
        <div class="form-row justify-content-center">
          <div class="form-group col-md-6">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
          </div>
        </div>
        <div class="form-row justify-content-center">
          <div class="form-group col-md-6">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="user@example.com" required>
          </div>
        </div>
        <div class="form-row justify-content-center">
          <div class="form-group col-md-6">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
          </div>
        </div>
        <div class="form-row justify-content-center">
          <div class="form-group col-md-6">
            <label for="passwordConfirm">Confirm Password</label>
            <input type="password" class="form-control" id="passwordConfirm" placeholder="Password" required>
          </div>
        </div>
        <div class="form-row justify-content-center">
          <button id="registerBtn" type="submit" class="btn btn-warning col-md-6">Register</button>
        </div>
      </div>
    </form>

 </div>

<?php include 'view/_footer.phtml'; ?>

<?php include 'view/_common_js.phtml'; ?>
  <script src="js/app.js"></script>
</body>
</html>
